[workspace]
resolver = "2"
members = ["img-gen", "generate", "spectrogram"]
default-members = ["img-gen", "generate"]

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
spectrogram = { path = "./spectrogram" }
clap = { version = "4.5.29", features = ["derive"] }
hound = "3.5.1"
indicatif = "0.17.11"
